// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * A Mimos user profile, keyed by the OIDC subject.
 */
export type UserProfile = {
    /**
     * Internal profile identifier.
     */
    id: string;
    /**
     * The OIDC subject (`sub`) the profile belongs to.
     */
    subjectId: string;
    /**
     * Name shown in the UI; initially the identity provider's username.
     */
    displayName: string;
    /**
     * When the profile was created.
     */
    createdAt: string;
};

/**
 * A plugin available on the instance and whether the caller turned it on (ADR-0013).
 */
export type UserPlugin = {
    /**
     * The plugin's manifest id.
     */
    id: string;
    /**
     * The plugin's manifest name.
     */
    name: string;
    /**
     * The plugin's documentation or project page, from its manifest.
     */
    homepageUrl?: string;
    /**
     * Whether the caller turned the plugin on. Plugins start off.
     */
    enabled: boolean;
};

export type UserPluginSetting = {
    enabled: boolean;
};

/**
 * A Mimos user as their household sees them.
 */
export type Person = {
    /**
     * The person's profile id.
     */
    id: string;
    displayName: string;
    /**
     * True when this is the caller.
     */
    you: boolean;
};

/**
 * The household the caller belongs to (ADR-0019).
 */
export type Household = {
    /**
     * Everyone in the household, by name.
     */
    members: Array<Person>;
};

/**
 * A single-use invite to a household.
 */
export type HouseholdInvite = {
    /**
     * The secret that makes the link `/app/join/{token}`. Shown once; only a hash is stored.
     */
    token: string;
    expiresAt: string;
};

export type HouseholdInviteToken = {
    token: string;
};

/**
 * An invite as the person it was given to sees it before joining.
 */
export type HouseholdInvitePreview = {
    /**
     * Everyone in the inviting household, by name.
     */
    members: Array<Person>;
    expiresAt: string;
    /**
     * True when the caller is already in the inviting household.
     */
    alreadyMember: boolean;
    /**
     * True when the caller's current household has other members, so joining means leaving it and bringing nothing. False when it is a household of one, whose recipes and ingredients come along.
     *
     */
    currentHouseholdShared: boolean;
};

/**
 * RFC 9457 problem details.
 */
export type Problem = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
};

/**
 * Per-serving nutrition for a recipe, or totals for a logged meal. Absent values are unknown, not zero.
 */
export type Nutrition = {
    /**
     * Kilocalories.
     */
    calories?: number;
    /**
     * Protein in grams.
     */
    proteinG?: number;
    /**
     * Carbohydrates in grams.
     */
    carbsG?: number;
    /**
     * Fat in grams.
     */
    fatG?: number;
};

/**
 * One ingredient line: an optional amount, an optional unit, and a name.
 */
export type IngredientQuantity = {
    /**
     * Amount of the ingredient; omitted for unmeasured ingredients ("salt, to taste"). Positive when present.
     */
    quantity?: number;
    /**
     * Unit of measure; omitted for countable ingredients ("2 eggs").
     */
    unit?: string;
    /**
     * Ingredient name as written in the recipe.
     */
    name: string;
    /**
     * Optional prep note shown after the name, like "minced" or "to serve".
     */
    note?: string;
    /**
     * Slug of the catalog ingredient this line counts as for calculated nutrition (see listIngredients); omitted when the line is not linked to one. A line links at most one of catalogSlug and recipeId.
     *
     */
    catalogSlug?: string;
    /**
     * Id of one of your own recipes this line is (see listMyRecipes), counted in servings of it (unit `servings`) for calculated nutrition, using that recipe's current per-serving nutrition; omitted when not linked to a recipe. A line links at most one of catalogSlug and recipeId. Library recipes, other users' recipes, the recipe itself, and a recipe that already uses this one cannot be linked. In an account export it is the `id` of another recipe in the same document.
     *
     */
    recipeId?: string;
};

/**
 * Where a recipe's nutrition comes from. MANUAL: the per-serving values its author typed. INGREDIENTS: calculated from the linked ingredient lines whenever the recipe is read; nutrition sent with the recipe is ignored.
 *
 */
export type NutritionSource = 'MANUAL' | 'INGREDIENTS';

/**
 * The amount a catalog ingredient's nutrition is for: 100 grams, 100 millilitres, or one piece.
 *
 */
export type NutritionBasis = 'PER_100_G' | 'PER_100_ML' | 'PER_PIECE';

/**
 * An ingredient with known nutrition for its basis, shared or the caller's own.
 */
export type CatalogIngredient = {
    slug: string;
    name: string;
    /**
     * True for the shared ingredients everyone sees, false for the caller's own.
     */
    isShared: boolean;
    basis: NutritionBasis;
    nutrition: Nutrition;
};

/**
 * One of the caller's own ingredients as submitted; nutrition needs all four values.
 */
export type IngredientInput = {
    name: string;
    basis: NutritionBasis;
    nutrition: Nutrition;
};

/**
 * The parts of a recipe its calculated nutrition depends on.
 */
export type NutritionEstimateInput = {
    servings: number;
    ingredients: Array<IngredientQuantity>;
};

/**
 * Whether an ingredient line counted toward calculated nutrition. UNMEASURED: linked but has no amount. NOT_LINKED: neither a catalogSlug nor a recipeId. UNIT_NOT_SUPPORTED: linked, but its unit does not fit the catalog entry's basis, or a recipe link is not in servings. NUTRITION_UNKNOWN: links a recipe whose per-serving calories, protein, carbs, or fat are not known (typed nutrition left blank, or nothing in it counts), so it adds nothing.
 *
 */
export type IngredientLineStatus = 'COUNTED' | 'UNMEASURED' | 'NOT_LINKED' | 'UNIT_NOT_SUPPORTED' | 'NUTRITION_UNKNOWN';

/**
 * Calculated per-serving nutrition, unknown when no line counted.
 */
export type NutritionEstimate = {
    nutrition: Nutrition;
    /**
     * One status per ingredient line, in the order sent.
     */
    lines: Array<IngredientLineStatus>;
};

/**
 * One instruction step; order is significant.
 */
export type RecipeStep = {
    instruction: string;
};

/**
 * A recipe as shown in lists and search results.
 */
export type RecipeSummary = {
    id: string;
    /**
     * Public URL slug; present only for curated library recipes.
     */
    slug?: string;
    title: string;
    description: string;
    /**
     * Number of servings the recipe makes.
     */
    servings: number;
    /**
     * True for curated library recipes, false for personal ones.
     */
    isLibrary: boolean;
    tags: Array<string>;
    nutrition: Nutrition;
};

/**
 * Everything needed to cook a recipe.
 */
export type RecipeDetail = {
    id: string;
    /**
     * Public URL slug; present only for curated library recipes.
     */
    slug?: string;
    title: string;
    description: string;
    servings: number;
    /**
     * Active preparation time, when known.
     */
    prepMinutes?: number;
    /**
     * Cooking time, when known.
     */
    cookMinutes?: number;
    isLibrary: boolean;
    tags: Array<string>;
    nutrition: Nutrition;
    nutritionSource: NutritionSource;
    ingredients: Array<IngredientQuantity>;
    steps: Array<RecipeStep>;
};

/**
 * A personal recipe as submitted by its author.
 */
export type RecipeInput = {
    title: string;
    description: string;
    servings: number;
    prepMinutes?: number;
    cookMinutes?: number;
    tags: Array<string>;
    nutrition: Nutrition;
    nutritionSource: NutritionSource;
    ingredients: Array<IngredientQuantity>;
    steps: Array<RecipeStep>;
};

/**
 * The meal slots a day is planned in.
 */
export type MealType = 'BREAKFAST' | 'LUNCH' | 'DINNER' | 'SNACK';

/**
 * One planned meal in a week.
 */
export type MealPlanEntry = {
    id: string;
    date: string;
    mealType: MealType;
    recipeId: string;
    /**
     * Title of the planned recipe at planning time.
     */
    recipeTitle: string;
    /**
     * How many servings of the recipe are planned.
     */
    servings: number;
};

/**
 * A week of planned meals, keyed by its Monday.
 */
export type MealPlan = {
    startDate: string;
    entries: Array<MealPlanEntry>;
};

export type MealPlanEntryInput = {
    date: string;
    mealType: MealType;
    recipeId: string;
    servings: number;
};

export type MealPlanEntryPatch = {
    servings: number;
};

/**
 * Suggestion cards for a week, from the instance's registered plugins (ADR-0006).
 */
export type PlanSuggestions = {
    suggestions: Array<PlanSuggestion>;
};

/**
 * One plugin suggestion card, advisory, validated by the server, and attributed to its plugin.
 */
export type PlanSuggestion = {
    /**
     * The plugin's manifest id.
     */
    pluginId: string;
    /**
     * The plugin's manifest name, shown as attribution.
     */
    pluginName: string;
    /**
     * Card headline (at most 80 characters).
     */
    title: string;
    /**
     * One-sentence explanation (at most 200 characters).
     */
    blurb?: string;
    /**
     * Short glyph shown next to the title (at most 8 characters).
     */
    icon?: string;
    /**
     * Proposed meals; apply them via the plan-entry endpoint.
     */
    entries: Array<PlanSuggestionEntry>;
};

/**
 * One proposed meal in a suggestion card.
 */
export type PlanSuggestionEntry = {
    date: string;
    mealType: MealType;
    /**
     * A curated library recipe (plugins see the library only).
     */
    recipeId: string;
    /**
     * Hydrated by the server from its own recipe data.
     */
    recipeTitle: string;
    servings: number;
};

/**
 * A week's plugin panels (ADR-0017).
 */
export type WeekPanels = {
    panels: Array<WeekPanel>;
};

/**
 * One plugin's panel for a week, validated by the server and attributed to its plugin. Render every string as plain text.
 *
 */
export type WeekPanel = {
    /**
     * The plugin's manifest id.
     */
    pluginId: string;
    /**
     * The plugin's manifest name, shown as attribution.
     */
    pluginName: string;
    summary?: PanelSummary;
    blocks: Array<PanelBlock>;
};

/**
 * The line shown while the panel is collapsed, such as a week's chosen country and its flag.
 */
export type PanelSummary = {
    /**
     * A short glyph (at most 8 characters), such as a flag emoji.
     */
    icon?: string;
    /**
     * At most 60 characters.
     */
    label: string;
};

export type PanelBlock = ({
    type: 'text';
} & PanelTextBlock) | ({
    type: 'highlight';
} & PanelHighlightBlock) | ({
    type: 'wheel';
} & PanelWheelBlock) | ({
    type: 'actions';
} & PanelActionsBlock);

export type PanelTextBlock = {
    type: string;
    text: string;
};

/**
 * One thing shown large, such as a chosen country.
 */
export type PanelHighlightBlock = {
    type: string;
    icon?: string;
    title: string;
    text?: string;
};

/**
 * A wheel of 2 to 60 segments. With landing, the wheel spins and stops on that segment, and the blocks after it are shown once it stops.
 *
 */
export type PanelWheelBlock = {
    type: string;
    segments: Array<PanelWheelSegment>;
    /**
     * Index into segments of where this spin stops.
     */
    landing?: number;
};

export type PanelWheelSegment = {
    label: string;
    icon?: string;
};

/**
 * A row of buttons; press one with pressWeekPanelAction.
 */
export type PanelActionsBlock = {
    type: string;
    actions: Array<PanelButton>;
};

export type PanelButton = {
    id: string;
    label: string;
    value?: string;
    /**
     * The one button to draw as the main action.
     */
    primary?: boolean;
};

/**
 * A button press, the id and value of a button from the plugin's panel.
 */
export type PanelAction = {
    id: string;
    value?: string;
};

/**
 * One aggregated shopping-list line.
 */
export type ShoppingListItem = {
    id: string;
    name: string;
    unit?: string;
    /**
     * Total measured amount across the week's recipes, rounded up to whole items for a line without a unit; omitted when every recipe leaves the ingredient unmeasured (ADR-0007).
     */
    quantity?: number;
    /**
     * Aisle grouping (Produce, Meat & Seafood, Dairy & Eggs, ...).
     */
    category: string;
    checked: boolean;
};

/**
 * A week's shopping list.
 */
export type ShoppingList = {
    startDate: string;
    generatedAt: string;
    items: Array<ShoppingListItem>;
};

export type ShoppingListItemPatch = {
    checked: boolean;
};

/**
 * One logged meal with its calorie/macro totals.
 */
export type MealLog = {
    id: string;
    date: string;
    mealType: MealType;
    /**
     * Referenced recipe, when the log came from a recipe.
     */
    recipeId?: string;
    description: string;
    servings: number;
    nutrition: Nutrition;
};

/**
 * A meal to log. With `recipeId` the nutrition is derived from the recipe; otherwise `description` and `nutrition` are required.
 *
 */
export type MealLogInput = {
    date: string;
    mealType: MealType;
    recipeId?: string;
    /**
     * Defaults to 1 when a recipeId is given.
     */
    servings?: number;
    /**
     * Required for ad-hoc logs; defaults to the recipe title otherwise.
     */
    description?: string;
    /**
     * Required for ad-hoc logs; ignored when a recipeId is given.
     */
    nutrition?: Nutrition;
};

/**
 * Calorie and macro totals for one day.
 */
export type DailyLogSummary = {
    date: string;
    calories: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
};

/**
 * One user's data, in export format version 3 (ADR-0011). Any change to this schema bumps the version and adds an upgrade step from the previous one.
 *
 */
export type AccountExport = {
    format: 'mimos.export';
    /**
     * The format version. This instance exports version 3.
     */
    version: number;
    exportedAt: string;
    /**
     * The user's own ingredients; recipe lines refer to them by slug.
     */
    ingredients: Array<ExportedIngredient>;
    recipes: Array<ExportedRecipe>;
    mealPlans: Array<ExportedMealPlan>;
    shoppingLists: Array<ExportedShoppingList>;
    mealLogs: Array<ExportedMealLog>;
};

/**
 * One of the user's own ingredients. `slug` is a key within the document; import assigns a new one.
 */
export type ExportedIngredient = {
    slug: string;
    name: string;
    basis: NutritionBasis;
    nutrition: Nutrition;
};

/**
 * A personal recipe. `id` is a key within the document; import assigns a new one. A line's recipeId names another recipe in the document by this id.
 *
 */
export type ExportedRecipe = {
    id: string;
    title: string;
    description: string;
    servings: number;
    prepMinutes?: number;
    cookMinutes?: number;
    tags: Array<string>;
    nutrition: Nutrition;
    nutritionSource: NutritionSource;
    ingredients: Array<IngredientQuantity>;
    steps: Array<RecipeStep>;
    createdAt: string;
    updatedAt: string;
};

/**
 * A week of planned meals, keyed by its Monday.
 */
export type ExportedMealPlan = {
    startDate: string;
    entries: Array<ExportedPlanEntry>;
};

/**
 * One planned meal. Exactly one of `recipeId` and `librarySlug` is present.
 */
export type ExportedPlanEntry = {
    date: string;
    mealType: MealType;
    /**
     * A recipe in this document's `recipes`.
     */
    recipeId?: string;
    /**
     * A curated library recipe, by its public slug.
     */
    librarySlug?: string;
    servings: number;
};

/**
 * A week's generated shopping list, as it was when exported.
 */
export type ExportedShoppingList = {
    startDate: string;
    generatedAt: string;
    items: Array<ExportedShoppingListItem>;
};

export type ExportedShoppingListItem = {
    name: string;
    unit?: string;
    /**
     * Omitted when every recipe leaves the ingredient unmeasured (ADR-0007).
     */
    quantity?: number;
    category: string;
    checked: boolean;
};

/**
 * One logged meal, with the nutrition copied when it was logged. At most one of `recipeId` and `librarySlug` is present; neither means an ad-hoc meal or one whose recipe was deleted.
 *
 */
export type ExportedMealLog = {
    date: string;
    mealType: MealType;
    /**
     * A recipe in this document's `recipes`.
     */
    recipeId?: string;
    /**
     * A curated library recipe, by its public slug.
     */
    librarySlug?: string;
    description: string;
    servings: number;
    nutrition: Nutrition;
    loggedAt: string;
};

/**
 * The outcome of an import.
 */
export type ImportReport = {
    /**
     * The format version of the imported document, before any upgrade.
     */
    sourceVersion: number;
    /**
     * Personal recipes imported.
     */
    recipes: number;
    /**
     * Planned meals imported.
     */
    plannedMeals: number;
    /**
     * Shopping lists imported.
     */
    shoppingLists: number;
    /**
     * Logged meals imported.
     */
    mealLogs: number;
    /**
     * Data that could not be carried over as it was, in plain words.
     */
    warnings: Array<string>;
};

export type RecipeId = string;

export type RecipeSlug = string;

export type IngredientSlug = string;

/**
 * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
 *
 */
export type PlanWeek = string;

export type EntryId = string;

export type ShoppingListItemId = string;

export type LogId = string;

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    403: Problem;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * The caller's profile.
     */
    200: UserProfile;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListMyPluginsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/plugins';
};

export type ListMyPluginsErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type ListMyPluginsError = ListMyPluginsErrors[keyof ListMyPluginsErrors];

export type ListMyPluginsResponses = {
    /**
     * The available plugins, each with the caller's choice.
     */
    200: Array<UserPlugin>;
};

export type ListMyPluginsResponse = ListMyPluginsResponses[keyof ListMyPluginsResponses];

export type UpdateMyPluginData = {
    body: UserPluginSetting;
    path: {
        /**
         * The plugin's manifest id.
         */
        pluginId: string;
    };
    query?: never;
    url: '/api/v1/me/plugins/{pluginId}';
};

export type UpdateMyPluginErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type UpdateMyPluginError = UpdateMyPluginErrors[keyof UpdateMyPluginErrors];

export type UpdateMyPluginResponses = {
    /**
     * The choice is saved.
     */
    204: void;
};

export type UpdateMyPluginResponse = UpdateMyPluginResponses[keyof UpdateMyPluginResponses];

export type GetHouseholdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/household';
};

export type GetHouseholdErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type GetHouseholdError = GetHouseholdErrors[keyof GetHouseholdErrors];

export type GetHouseholdResponses = {
    /**
     * The caller's household.
     */
    200: Household;
};

export type GetHouseholdResponse = GetHouseholdResponses[keyof GetHouseholdResponses];

export type CreateHouseholdInviteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/household/invites';
};

export type CreateHouseholdInviteErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type CreateHouseholdInviteError = CreateHouseholdInviteErrors[keyof CreateHouseholdInviteErrors];

export type CreateHouseholdInviteResponses = {
    /**
     * The invite, with its one-time token.
     */
    201: HouseholdInvite;
};

export type CreateHouseholdInviteResponse = CreateHouseholdInviteResponses[keyof CreateHouseholdInviteResponses];

export type PreviewHouseholdInviteData = {
    body: HouseholdInviteToken;
    path?: never;
    query?: never;
    url: '/api/v1/household/invites/preview';
};

export type PreviewHouseholdInviteErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    410: Problem;
};

export type PreviewHouseholdInviteError = PreviewHouseholdInviteErrors[keyof PreviewHouseholdInviteErrors];

export type PreviewHouseholdInviteResponses = {
    /**
     * The invite's household and what joining would do.
     */
    200: HouseholdInvitePreview;
};

export type PreviewHouseholdInviteResponse = PreviewHouseholdInviteResponses[keyof PreviewHouseholdInviteResponses];

export type JoinHouseholdData = {
    body: HouseholdInviteToken;
    path?: never;
    query?: never;
    url: '/api/v1/household/join';
};

export type JoinHouseholdErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    409: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    410: Problem;
};

export type JoinHouseholdError = JoinHouseholdErrors[keyof JoinHouseholdErrors];

export type JoinHouseholdResponses = {
    /**
     * The household the caller is now in.
     */
    200: Household;
};

export type JoinHouseholdResponse = JoinHouseholdResponses[keyof JoinHouseholdResponses];

export type LeaveHouseholdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/household/leave';
};

export type LeaveHouseholdErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    409: Problem;
};

export type LeaveHouseholdError = LeaveHouseholdErrors[keyof LeaveHouseholdErrors];

export type LeaveHouseholdResponses = {
    /**
     * The caller's new household of one.
     */
    200: Household;
};

export type LeaveHouseholdResponse = LeaveHouseholdResponses[keyof LeaveHouseholdResponses];

export type ExportAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/account/export';
};

export type ExportAccountErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type ExportAccountError = ExportAccountErrors[keyof ExportAccountErrors];

export type ExportAccountResponses = {
    /**
     * The caller's data in the current export format version.
     */
    200: AccountExport;
};

export type ExportAccountResponse = ExportAccountResponses[keyof ExportAccountResponses];

export type ImportAccountData = {
    /**
     * An `AccountExport` document of any supported version. Declared free-form because older versions do not match the current schema.
     *
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/import';
};

export type ImportAccountErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    409: Problem;
};

export type ImportAccountError = ImportAccountErrors[keyof ImportAccountErrors];

export type ImportAccountResponses = {
    /**
     * What was imported, and what could not be.
     */
    200: ImportReport;
};

export type ImportAccountResponse = ImportAccountResponses[keyof ImportAccountResponses];

export type ListMyRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive filter on title, description, tags, and ingredient names.
         */
        q?: string;
    };
    url: '/api/v1/recipes';
};

export type ListMyRecipesErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type ListMyRecipesError = ListMyRecipesErrors[keyof ListMyRecipesErrors];

export type ListMyRecipesResponses = {
    /**
     * The caller's personal recipes, newest first.
     */
    200: Array<RecipeSummary>;
};

export type ListMyRecipesResponse = ListMyRecipesResponses[keyof ListMyRecipesResponses];

export type CreateRecipeData = {
    body: RecipeInput;
    path?: never;
    query?: never;
    url: '/api/v1/recipes';
};

export type CreateRecipeErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type CreateRecipeError = CreateRecipeErrors[keyof CreateRecipeErrors];

export type CreateRecipeResponses = {
    /**
     * The created recipe.
     */
    201: RecipeDetail;
};

export type CreateRecipeResponse = CreateRecipeResponses[keyof CreateRecipeResponses];

export type DeleteRecipeData = {
    body?: never;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/api/v1/recipes/{recipeId}';
};

export type DeleteRecipeErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    403: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type DeleteRecipeError = DeleteRecipeErrors[keyof DeleteRecipeErrors];

export type DeleteRecipeResponses = {
    /**
     * Deleted.
     */
    204: void;
};

export type DeleteRecipeResponse = DeleteRecipeResponses[keyof DeleteRecipeResponses];

export type GetRecipeData = {
    body?: never;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/api/v1/recipes/{recipeId}';
};

export type GetRecipeErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type GetRecipeError = GetRecipeErrors[keyof GetRecipeErrors];

export type GetRecipeResponses = {
    /**
     * The recipe.
     */
    200: RecipeDetail;
};

export type GetRecipeResponse = GetRecipeResponses[keyof GetRecipeResponses];

export type ReplaceRecipeData = {
    body: RecipeInput;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/api/v1/recipes/{recipeId}';
};

export type ReplaceRecipeErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    403: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type ReplaceRecipeError = ReplaceRecipeErrors[keyof ReplaceRecipeErrors];

export type ReplaceRecipeResponses = {
    /**
     * The replaced recipe.
     */
    200: RecipeDetail;
};

export type ReplaceRecipeResponse = ReplaceRecipeResponses[keyof ReplaceRecipeResponses];

export type EstimateRecipeNutritionData = {
    body: NutritionEstimateInput;
    path?: never;
    query?: never;
    url: '/api/v1/recipes/nutrition-estimate';
};

export type EstimateRecipeNutritionErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type EstimateRecipeNutritionError = EstimateRecipeNutritionErrors[keyof EstimateRecipeNutritionErrors];

export type EstimateRecipeNutritionResponses = {
    /**
     * The calculated nutrition and each line's status.
     */
    200: NutritionEstimate;
};

export type EstimateRecipeNutritionResponse = EstimateRecipeNutritionResponses[keyof EstimateRecipeNutritionResponses];

export type ListIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive filter on name and slug.
         */
        q?: string;
    };
    url: '/api/v1/ingredients';
};

export type ListIngredientsErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type ListIngredientsError = ListIngredientsErrors[keyof ListIngredientsErrors];

export type ListIngredientsResponses = {
    /**
     * Ingredients, sorted by name.
     */
    200: Array<CatalogIngredient>;
};

export type ListIngredientsResponse = ListIngredientsResponses[keyof ListIngredientsResponses];

export type CreateIngredientData = {
    body: IngredientInput;
    path?: never;
    query?: never;
    url: '/api/v1/ingredients';
};

export type CreateIngredientErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type CreateIngredientError = CreateIngredientErrors[keyof CreateIngredientErrors];

export type CreateIngredientResponses = {
    /**
     * The created ingredient.
     */
    201: CatalogIngredient;
};

export type CreateIngredientResponse = CreateIngredientResponses[keyof CreateIngredientResponses];

export type DeleteIngredientData = {
    body?: never;
    path: {
        ingredientSlug: string;
    };
    query?: never;
    url: '/api/v1/ingredients/{ingredientSlug}';
};

export type DeleteIngredientErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    403: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type DeleteIngredientError = DeleteIngredientErrors[keyof DeleteIngredientErrors];

export type DeleteIngredientResponses = {
    /**
     * Deleted.
     */
    204: void;
};

export type DeleteIngredientResponse = DeleteIngredientResponses[keyof DeleteIngredientResponses];

export type ReplaceIngredientData = {
    body: IngredientInput;
    path: {
        ingredientSlug: string;
    };
    query?: never;
    url: '/api/v1/ingredients/{ingredientSlug}';
};

export type ReplaceIngredientErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    403: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type ReplaceIngredientError = ReplaceIngredientErrors[keyof ReplaceIngredientErrors];

export type ReplaceIngredientResponses = {
    /**
     * The replaced ingredient.
     */
    200: CatalogIngredient;
};

export type ReplaceIngredientResponse = ReplaceIngredientResponses[keyof ReplaceIngredientResponses];

export type ListLibraryRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive filter on title, description, tags, and ingredient names.
         */
        q?: string;
    };
    url: '/api/v1/recipes/library';
};

export type ListLibraryRecipesErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type ListLibraryRecipesError = ListLibraryRecipesErrors[keyof ListLibraryRecipesErrors];

export type ListLibraryRecipesResponses = {
    /**
     * Library recipes, sorted by title.
     */
    200: Array<RecipeSummary>;
};

export type ListLibraryRecipesResponse = ListLibraryRecipesResponses[keyof ListLibraryRecipesResponses];

export type ListPublicRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive filter on title, description, tags, and ingredient names.
         */
        q?: string;
    };
    url: '/api/v1/public/recipes';
};

export type ListPublicRecipesResponses = {
    /**
     * Library recipes, sorted by title.
     */
    200: Array<RecipeSummary>;
};

export type ListPublicRecipesResponse = ListPublicRecipesResponses[keyof ListPublicRecipesResponses];

export type GetPublicRecipeData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/public/recipes/{slug}';
};

export type GetPublicRecipeErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type GetPublicRecipeError = GetPublicRecipeErrors[keyof GetPublicRecipeErrors];

export type GetPublicRecipeResponses = {
    /**
     * The recipe.
     */
    200: RecipeDetail;
};

export type GetPublicRecipeResponse = GetPublicRecipeResponses[keyof GetPublicRecipeResponses];

export type GetMealPlanData = {
    body?: never;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}';
};

export type GetMealPlanErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type GetMealPlanError = GetMealPlanErrors[keyof GetMealPlanErrors];

export type GetMealPlanResponses = {
    /**
     * The week's plan.
     */
    200: MealPlan;
};

export type GetMealPlanResponse = GetMealPlanResponses[keyof GetMealPlanResponses];

export type AddMealPlanEntryData = {
    body: MealPlanEntryInput;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/entries';
};

export type AddMealPlanEntryErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type AddMealPlanEntryError = AddMealPlanEntryErrors[keyof AddMealPlanEntryErrors];

export type AddMealPlanEntryResponses = {
    /**
     * The created entry.
     */
    201: MealPlanEntry;
};

export type AddMealPlanEntryResponse = AddMealPlanEntryResponses[keyof AddMealPlanEntryResponses];

export type DeleteMealPlanEntryData = {
    body?: never;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
        entryId: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/entries/{entryId}';
};

export type DeleteMealPlanEntryErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type DeleteMealPlanEntryError = DeleteMealPlanEntryErrors[keyof DeleteMealPlanEntryErrors];

export type DeleteMealPlanEntryResponses = {
    /**
     * Removed.
     */
    204: void;
};

export type DeleteMealPlanEntryResponse = DeleteMealPlanEntryResponses[keyof DeleteMealPlanEntryResponses];

export type UpdateMealPlanEntryData = {
    body: MealPlanEntryPatch;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
        entryId: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/entries/{entryId}';
};

export type UpdateMealPlanEntryErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type UpdateMealPlanEntryError = UpdateMealPlanEntryErrors[keyof UpdateMealPlanEntryErrors];

export type UpdateMealPlanEntryResponses = {
    /**
     * The updated entry.
     */
    200: MealPlanEntry;
};

export type UpdateMealPlanEntryResponse = UpdateMealPlanEntryResponses[keyof UpdateMealPlanEntryResponses];

export type GetPlanSuggestionsData = {
    body?: never;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/suggestions';
};

export type GetPlanSuggestionsErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type GetPlanSuggestionsError = GetPlanSuggestionsErrors[keyof GetPlanSuggestionsErrors];

export type GetPlanSuggestionsResponses = {
    /**
     * Cards from the caller's healthy plugins, in registration order.
     */
    200: PlanSuggestions;
};

export type GetPlanSuggestionsResponse = GetPlanSuggestionsResponses[keyof GetPlanSuggestionsResponses];

export type GetWeekPanelsData = {
    body?: never;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/panels';
};

export type GetWeekPanelsErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type GetWeekPanelsError = GetWeekPanelsErrors[keyof GetWeekPanelsErrors];

export type GetWeekPanelsResponses = {
    /**
     * Panels from the caller's healthy plugins.
     */
    200: WeekPanels;
};

export type GetWeekPanelsResponse = GetWeekPanelsResponses[keyof GetWeekPanelsResponses];

export type PressWeekPanelActionData = {
    body: PanelAction;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
        /**
         * The plugin's manifest id, as in the panel's pluginId.
         */
        pluginId: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/panels/{pluginId}/actions';
};

export type PressWeekPanelActionErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    502: Problem;
};

export type PressWeekPanelActionError = PressWeekPanelActionErrors[keyof PressWeekPanelActionErrors];

export type PressWeekPanelActionResponses = {
    /**
     * The panel after the action.
     */
    200: WeekPanel;
};

export type PressWeekPanelActionResponse = PressWeekPanelActionResponses[keyof PressWeekPanelActionResponses];

export type GetShoppingListData = {
    body?: never;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/shopping-list';
};

export type GetShoppingListErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type GetShoppingListError = GetShoppingListErrors[keyof GetShoppingListErrors];

export type GetShoppingListResponses = {
    /**
     * The week's shopping list.
     */
    200: ShoppingList;
};

export type GetShoppingListResponse = GetShoppingListResponses[keyof GetShoppingListResponses];

export type GenerateShoppingListData = {
    body?: never;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/shopping-list';
};

export type GenerateShoppingListErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type GenerateShoppingListError = GenerateShoppingListErrors[keyof GenerateShoppingListErrors];

export type GenerateShoppingListResponses = {
    /**
     * The generated shopping list.
     */
    200: ShoppingList;
};

export type GenerateShoppingListResponse = GenerateShoppingListResponses[keyof GenerateShoppingListResponses];

export type UpdateShoppingListItemData = {
    body: ShoppingListItemPatch;
    path: {
        /**
         * The Monday that starts the planned week, as an ISO date (2026-10-05). Any other day is rejected with a 400.
         *
         */
        startDate: string;
        itemId: string;
    };
    query?: never;
    url: '/api/v1/plans/{startDate}/shopping-list/items/{itemId}';
};

export type UpdateShoppingListItemErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type UpdateShoppingListItemError = UpdateShoppingListItemErrors[keyof UpdateShoppingListItemErrors];

export type UpdateShoppingListItemResponses = {
    /**
     * The updated item.
     */
    200: ShoppingListItem;
};

export type UpdateShoppingListItemResponse = UpdateShoppingListItemResponses[keyof UpdateShoppingListItemResponses];

export type ListMealLogsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
    };
    url: '/api/v1/logs';
};

export type ListMealLogsErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type ListMealLogsError = ListMealLogsErrors[keyof ListMealLogsErrors];

export type ListMealLogsResponses = {
    /**
     * Logs in the range (inclusive), ordered by date and meal.
     */
    200: Array<MealLog>;
};

export type ListMealLogsResponse = ListMealLogsResponses[keyof ListMealLogsResponses];

export type CreateMealLogData = {
    body: MealLogInput;
    path?: never;
    query?: never;
    url: '/api/v1/logs';
};

export type CreateMealLogErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type CreateMealLogError = CreateMealLogErrors[keyof CreateMealLogErrors];

export type CreateMealLogResponses = {
    /**
     * The created log entry.
     */
    201: MealLog;
};

export type CreateMealLogResponse = CreateMealLogResponses[keyof CreateMealLogResponses];

export type DeleteMealLogData = {
    body?: never;
    path: {
        logId: string;
    };
    query?: never;
    url: '/api/v1/logs/{logId}';
};

export type DeleteMealLogErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    404: Problem;
};

export type DeleteMealLogError = DeleteMealLogErrors[keyof DeleteMealLogErrors];

export type DeleteMealLogResponses = {
    /**
     * Deleted.
     */
    204: void;
};

export type DeleteMealLogResponse = DeleteMealLogResponses[keyof DeleteMealLogResponses];

export type SummarizeMealLogsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
    };
    url: '/api/v1/logs/summary';
};

export type SummarizeMealLogsErrors = {
    /**
     * An RFC 9457 problem-details error.
     */
    400: Problem;
    /**
     * An RFC 9457 problem-details error.
     */
    401: Problem;
};

export type SummarizeMealLogsError = SummarizeMealLogsErrors[keyof SummarizeMealLogsErrors];

export type SummarizeMealLogsResponses = {
    /**
     * Totals per day in the range (inclusive). Days without logs are omitted.
     */
    200: Array<DailyLogSummary>;
};

export type SummarizeMealLogsResponse = SummarizeMealLogsResponses[keyof SummarizeMealLogsResponses];
