// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Declares the plugin to the instance.
 */
export type PluginManifest = {
    schema: 'mimos.plugin.manifest/v1';
    /**
     * Unique per instance; duplicate ids are a configuration error.
     */
    id: string;
    /**
     * Human-readable name, shown as attribution on cards.
     */
    name: string;
    /**
     * The plugin's own version (not the API version).
     */
    version: string;
    /**
     * Extension API major versions this plugin speaks.
     */
    apiVersions: Array<string>;
    /**
     * Capabilities the plugin provides. v1 defines one: `plan-suggestions`. Unknown capabilities are ignored with a warning (a newer plugin on an older core degrades, not fails).
     *
     */
    capabilities: Array<string>;
    /**
     * Documentation or project page.
     */
    homepageUrl?: string;
};

/**
 * Everything the plugin may know about the request.
 */
export type SuggestionContext = {
    /**
     * The Monday of the week being planned.
     */
    weekStartDate: string;
    /**
     * Meals already in the plan. `recipeId` is present only where the planned recipe is itself a library recipe — personal recipes contribute their shape, never their identity.
     *
     */
    plannedSlots: Array<PlannedSlot>;
    /**
     * The curated library catalog (the only recipes the plugin sees).
     */
    libraryRecipes: Array<LibraryRecipe>;
};

export type PlannedSlot = {
    date: string;
    mealType: MealType;
    servings: number;
    recipeId?: string;
};

export type LibraryRecipe = {
    id: string;
    title: string;
    tags: Array<string>;
    servings: number;
};

export type MealType = 'BREAKFAST' | 'LUNCH' | 'DINNER' | 'SNACK';

export type PluginSuggestions = {
    suggestions: Array<PluginSuggestionCard>;
};

/**
 * One suggestion card. Mimos validates every field: title at most 80 characters (required), blurb at most 200, icon at most 8 (a short glyph), at most 5 cards per response and 7 entries per card; each entry must fall inside the plan week, use a valid meal type, reference a library recipe from the context, and carry servings in (0, 100]. Invalid entries are dropped; a card left with no entries is dropped.
 *
 */
export type PluginSuggestionCard = {
    title: string;
    blurb?: string;
    icon?: string;
    entries: Array<SuggestedEntry>;
};

export type SuggestedEntry = {
    date: string;
    mealType: MealType;
    /**
     * Must reference a library recipe from the context.
     */
    recipeId: string;
    servings: number;
};

export type GetManifestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manifest';
};

export type GetManifestResponses = {
    /**
     * The manifest.
     */
    200: PluginManifest;
};

export type GetManifestResponse = GetManifestResponses[keyof GetManifestResponses];

export type CreatePlanSuggestionsData = {
    body: SuggestionContext;
    path?: never;
    query?: never;
    url: '/v1/plan-suggestions';
};

export type CreatePlanSuggestionsResponses = {
    /**
     * Suggestion cards (may be empty).
     */
    200: PluginSuggestions;
};

export type CreatePlanSuggestionsResponse = CreatePlanSuggestionsResponses[keyof CreatePlanSuggestionsResponses];
