// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Declares the plugin to the instance.
 */
export type PluginManifest = {
    schema: 'mimos.plugin.manifest/v1';
    /**
     * Unique per instance; duplicate ids are a configuration error.
     */
    id: string;
    /**
     * Human-readable name, shown as attribution on cards.
     */
    name: string;
    /**
     * The plugin's own version (not the API version).
     */
    version: string;
    /**
     * Extension API major versions this plugin speaks.
     */
    apiVersions: Array<string>;
    /**
     * Capabilities the plugin provides. v1 defines `plan-suggestions` and `week-panel`. Unknown capabilities are ignored with a warning (a newer plugin on an older core degrades, not fails).
     *
     */
    capabilities: Array<string>;
    /**
     * Documentation or project page.
     */
    homepageUrl?: string;
};

/**
 * Everything the plugin may know about the request.
 */
export type SuggestionContext = {
    subject?: Subject;
    /**
     * The Monday of the week being planned.
     */
    weekStartDate: string;
    /**
     * Meals already in the plan. `recipeId` is present only where the planned recipe is itself a library recipe — personal recipes contribute their shape, never their identity.
     *
     */
    plannedSlots: Array<PlannedSlot>;
    /**
     * The curated library catalog (the only recipes the plugin sees).
     */
    libraryRecipes: Array<LibraryRecipe>;
};

export type PlannedSlot = {
    date: string;
    mealType: MealType;
    servings: number;
    recipeId?: string;
};

export type LibraryRecipe = {
    id: string;
    title: string;
    tags: Array<string>;
    servings: number;
};

export type MealType = 'BREAKFAST' | 'LUNCH' | 'DINNER' | 'SNACK';

export type PluginSuggestions = {
    suggestions: Array<PluginSuggestionCard>;
};

/**
 * One suggestion card. Mimos validates every field: title at most 80 characters (required), blurb at most 200, icon at most 8 (a short glyph), at most 5 cards per response and 7 entries per card; each entry must fall inside the plan week, use a valid meal type, reference a library recipe from the context, and carry servings in (0, 100]. Invalid entries are dropped; a card left with no entries is dropped.
 *
 */
export type PluginSuggestionCard = {
    title: string;
    blurb?: string;
    icon?: string;
    entries: Array<SuggestedEntry>;
};

export type SuggestedEntry = {
    date: string;
    mealType: MealType;
    /**
     * Must reference a library recipe from the context.
     */
    recipeId: string;
    servings: number;
};

/**
 * The user's household, as a pseudonym: stable for one household and one plugin, different for every plugin, unrelated to any identity Mimos or its identity provider holds. A user on their own is a household of one, so for them it identifies that user; in a shared household every member is sent the same subject. Sent with every request Mimos makes on a user's behalf (optional on plan-suggestions only for older cores).
 *
 */
export type Subject = string;

export type WeekPanelRequest = {
    subject: Subject;
    /**
     * The Monday of the week the panel is for.
     */
    weekStartDate: string;
    action?: PanelAction;
};

/**
 * A button the user pressed: the `id` and `value` of an action this plugin rendered. They pass through the user's browser, so treat them as untrusted input.
 *
 */
export type PanelAction = {
    id: string;
    value?: string;
};

/**
 * A declarative panel, validated by Mimos and rendered as plain text. At most 8 blocks. An invalid block, or one of a type this Mimos does not know, is dropped; an invalid summary is dropped.
 *
 */
export type WeekPanel = {
    summary?: PanelSummary;
    blocks: Array<PanelBlock>;
};

/**
 * The line shown while the panel is collapsed.
 */
export type PanelSummary = {
    /**
     * A short glyph, such as a flag emoji.
     */
    icon?: string;
    label: string;
};

export type PanelBlock = ({
    type: 'text';
} & TextBlock) | ({
    type: 'highlight';
} & HighlightBlock) | ({
    type: 'wheel';
} & WheelBlock) | ({
    type: 'actions';
} & ActionsBlock);

export type TextBlock = {
    type: 'text';
    text: string;
};

/**
 * One thing shown large, such as a chosen country.
 */
export type HighlightBlock = {
    type: 'highlight';
    icon?: string;
    title: string;
    text?: string;
};

/**
 * A wheel of segments. With `landing`, the wheel spins and stops on that segment, and the blocks after it appear once it stops.
 *
 */
export type WheelBlock = {
    type: 'wheel';
    segments: Array<WheelSegment>;
    /**
     * Index into `segments`.
     */
    landing?: number;
};

export type WheelSegment = {
    label: string;
    icon?: string;
};

/**
 * A row of buttons. Pressing one sends its `id` and `value` back as the request's `action`.
 */
export type ActionsBlock = {
    type: 'actions';
    actions: Array<PanelButton>;
};

export type PanelButton = {
    id: string;
    label: string;
    value?: string;
    /**
     * The one button to draw as the main action.
     */
    primary?: boolean;
};

export type GetManifestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manifest';
};

export type GetManifestResponses = {
    /**
     * The manifest.
     */
    200: PluginManifest;
};

export type GetManifestResponse = GetManifestResponses[keyof GetManifestResponses];

export type CreatePlanSuggestionsData = {
    body: SuggestionContext;
    path?: never;
    query?: never;
    url: '/v1/plan-suggestions';
};

export type CreatePlanSuggestionsResponses = {
    /**
     * Suggestion cards (may be empty).
     */
    200: PluginSuggestions;
};

export type CreatePlanSuggestionsResponse = CreatePlanSuggestionsResponses[keyof CreatePlanSuggestionsResponses];

export type RenderWeekPanelData = {
    body: WeekPanelRequest;
    path?: never;
    query?: never;
    url: '/v1/week-panel';
};

export type RenderWeekPanelResponses = {
    /**
     * The panel.
     */
    200: WeekPanel;
};

export type RenderWeekPanelResponse = RenderWeekPanelResponses[keyof RenderWeekPanelResponses];
